name: local
variables:
  - name: ACCESS_TOKEN
    value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzg2NjAxOTgwLCJpYXQiOjE3ODY2MDEwODAsImp0aSI6IjVmZWY3ODg0ODlmMzQ4ZjliNTQwMzFmYjYxMWZhZGQ2IiwidXNlcl9pZCI6IjMifQ.wzM2qmFT5w32Tjwq63DRXSinG-n9MPT67v4zB1P7k2A
  - name: REFRESH_TOKEN
    value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4NzIwNTg4MCwiaWF0IjoxNzg2NjAxMDgwLCJqdGkiOiIyNTZhNjgyNWQ0YjI0NzYzYjdiYzFkNTNlY2JjYzYyOCIsInVzZXJfaWQiOiIzIn0.Aek6gCITGy2NeUwpND7lb61y6JbMpQAt76wyf2lioAc
